# Generated by Django 5.0.1 on 2024-02-08 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=200)),
                ('timestamp', models.IntegerField()),
                ('altText', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
